// 首頁所有區塊的預設內容 — Home.tsx 與後台 HomeContentTab 共用的單一真相來源。
// 後台儲存的內容（DB）會覆蓋這裡的預設值；未儲存過的區塊則顯示這裡的文字。
export const DEFAULTS = {
  hero: {
    badgeText: '12 年零售高管 · 親手養出 2 個營利中的 AI 音樂頻道',
    title: '不露臉、不唱歌、不懂樂理\n用 AI 打造會自動賺錢的',
    titleHighlight: '音樂頻道',
    subtitle: '我已經驗證 2 次：AI 音樂廠牌「唯夏 VXYA Music」30 天開通 YouTube 營利，「ChillNight」每月領被動分潤。現在，我把整套可複製的 SOP 教給你。',
    ctaText: '免費領取 AI 音樂變現指南',
    ctaSecondary: '試聽代表作品',
    photoBadge: '',
    trustBadges: '✓ 30 天開通營利,✓ 不需露臉出鏡,✓ 零樂理基礎,✓ 完整 SOP 複製',
  },
  painPoints: {
    label: '這是為你準備的',
    sectionTitle: '如果你也卡在這些地方',
    painsTitle: '你是不是也曾經……',
    pains: [
      '部落格、短影音都試過，流量卻一直起不來',
      '想做被動收入，卻不知道從哪一步開始',
      '不想露臉、沒有才藝，覺得自己「做不了內容」',
      '只有下班後一兩小時，怕投入了卻沒成果',
    ],
    fitTitle: '那這套方法正好適合你',
    fits: [
      '想用下班時間，打造會累積的內容資產',
      '零基礎、不懂樂理、不想露臉都 OK',
      '願意照 SOP 一步步做，而不是只想快速致富',
      '想要一條已被驗證、可複製的路，少走彎路',
    ],
  },
  works: {
    label: '代表作品 · ORIGINAL WORKS',
    sectionTitle: '點開就懂——這些都是 AI 做的原創音樂',
    sectionSubtitle: '唯夏 VXYA Music × ChillNight 的原創 MV，每一首都是頻道實際在跑、實際在累積收益的內容。',
    featuredId: 'V2qLxxpaZxo',
    featuredTitle: '《辭雪樓》戲腔古典情歌 · 破 3 萬觀看',
    items: [
      { id: 'igtxFHoR-3k', title: '《夢蝶》', tag: '古典戲腔', cover: '/images/works/mengdie.jpg' },
      { id: 'lC1DMjpd5Bs', title: '《破雲槍》', tag: '古風熱血戰歌', cover: '/images/works/poyunqiang.jpg' },
      { id: '0GVhRwCAWi4', title: '《長風入喉》', tag: '古風熱血戰歌', cover: '/images/works/changfeng.jpg' },
      { id: 'dOYDE3Lr2ds', title: '《舊戲辭》', tag: '古典戲腔', cover: '/images/works/jiuxici.jpg' },
      { id: 'i_4_dEzL_vc', title: '《醉月仙》', tag: '仙俠浪漫情歌', cover: '/images/works/zuiyuexian.jpg' },
    ],
  },
  channels: {
    label: '真實戰績',
    sectionTitle: '我不只教學，我自己就在做',
    sectionSubtitle: '這兩個頻道都是我親手從 0 養起，現在仍在持續更新、持續產生收益。',
    items: [
      {
        name: '唯夏 VXYA Music',
        tag: 'AI 音樂廠牌・旗下多位虛擬歌手',
        desc: '我從 0 打造的 AI 音樂廠牌，頻道 30 天開通 YouTube 營利。旗艦歌手「唯夏」單曲《辭雪樓》破 3 萬觀看，旗下持續擴張更多虛擬歌手。',
        metric: '30 天',
        metricLabel: '開通營利',
        url: 'https://www.youtube.com/@VXYA_officialmusic',
        accent: 'violet',
        avatar: '/images/channels/vxya.jpg',
      },
      {
        name: 'ChillNight AI Music',
        tag: '不露臉純音樂頻道',
        desc: '主打深夜放鬆、Trap、國風說唱的不露臉音樂頻道，用 AI 量產長片合輯與 Shorts，穩定累積 YouTube 廣告分潤。',
        metric: 'NT$2萬+',
        metricLabel: '月被動分潤',
        url: 'https://www.youtube.com/@chillnightAImusic',
        accent: 'fuchsia',
        avatar: '/images/channels/chillnight.jpg',
      },
    ],
  },
  students: {
    label: '學員實證',
    sectionTitle: '不是只有我做得到，學員也跟著做出來了',
    sectionSubtitle: '4 月開課的學員，零基礎跟著 SOP 操作，一個多月就看到成果。',
    items: [
      {
        name: '流行引力 Pulse Gravity',
        handle: '@PulseGravity',
        avatar: '/images/channels/pulsegravity.jpg',
        niche: '國風史詩電音 · 布袋戲戰鼓',
        stat: '1,600+ 訂閱 · 129 部影片',
        result: '4 月零基礎加入，5 月中開通 YouTube 營利，並已開放頻道會員。',
        url: 'https://www.youtube.com/@PulseGravity',
        accent: 'violet',
      },
      {
        name: '光室謐靜',
        handle: '@lightzen108',
        avatar: '/images/channels/lightzen108.jpg',
        niche: '療癒頻率音樂 · 助眠冥想',
        stat: '450+ 訂閱 · 21 部影片',
        result: '4 月加入，從 0 起步穩定產出，即將達成 YouTube 營利門檻。',
        url: 'https://www.youtube.com/@lightzen108',
        accent: 'fuchsia',
      },
    ],
  },
  howItWorks: {
    label: '可複製的系統',
    sectionTitle: '3 步驟打造你的 AI 音樂變現頻道',
    sectionSubtitle: '從選題到上架營利，一套我親自跑過兩次的標準流程。',
    steps: [
      { icon: 'Target', title: '選對賺錢的利基', description: '用數據判斷哪種音樂風格有流量、有廣告價值，先確認方向再動手，不做沒人聽的內容。' },
      { icon: 'Cpu', title: 'AI 量產音樂與視覺', description: '用 Suno 生成原創音樂、AI 生成封面與 MV，一個人就能維持每日更新的產能。' },
      { icon: 'TrendingUp', title: '上架營利、放大收益', description: '開通 YouTube 營利後，疊加聯盟行銷、音樂授權與品牌合作，把單一頻道變成多重收入。' },
    ],
  },
  revenueProof: {
    label: '真實收益實證',
    sectionTitle: '不是喊口號，是真的有進帳',
    sectionSubtitle: '以下皆為真實後台截圖，非模擬數據。多元收入管道持續累積中。',
    items: [
      { img: '/images/proof/revenue_yt.jpg', title: 'YouTube 廣告收益', amount: 'US$500–945 / 月', tag: 'YouTube AdSense' },
      { img: '/images/proof/revenue_shopee.jpg', title: '蝦皮分潤收益', amount: 'NT$1.7 萬+ / 月', tag: 'Shopee Affiliate' },
      { img: '/images/proof/revenue_portaly.jpg', title: '虛擬 IP 周邊販售', amount: 'NT$5,357', tag: 'Portaly 金流' },
    ],
    note: '※ 以上為老J 本人頻道與品牌的真實後台截圖；個人成果會因投入與執行而異，不代表保證收益。',
  },
  course: {
    label: '線上課程',
    sectionTitle: '用 YouTube 打造你的第一條被動收入',
    sectionSubtitle: '從 0 到開通營利的完整 SOP：選題對標 → Suno 生成音樂 → 影片製作 → 上架 YouTube → 台灣收款。每一步都有手把手教學，跟著做就能上手。',
    priceLabel: '搶先優惠價',
    price: 'NT$3,888',
    priceOriginal: '定價 NT$9,950',
    priceNote: '每兩個月階梯漲價，11/1 起恢復完整定價',
    ctaText: '查看課程完整內容',
    url: 'https://ebook.oldjailab.com/',
    features: [
      '從零到營利的完整 SOP 教學電子書（價值 $1,990）',
      'Suno 專用做歌詞小工具（價值 $990）',
      '專屬教學社群，操作有問題隨時問（價值 $1,990）',
      '手把手影片教學，邊看邊做（價值 $990）',
      '台灣收款完整教學 AdSense / PIN / 電匯（價值 $990）',
      '未來新被動收入教學，免費更新（價值 $2,990）',
    ],
  },
  guarantee: {
    label: '安心入手 · 0 壓力',
    sectionTitle: '先免費試，覺得有料再決定',
    subtitle: '不用一開始就掏錢冒險——先領免費指南，覺得這套打法對你有用，再考慮完整課程。買了之後也不是丟著不管：',
    items: [
      { title: '先試再買', desc: '免費指南先看，判斷適不適合你，零風險。' },
      { title: '卡關有人答', desc: '專屬社群陪你做，操作卡住隨時發問。' },
      { title: '持續更新', desc: '未來新的被動收入教學，免費拿。' },
    ],
    buttonText: '先免費領取指南',
  },
  leadMagnet: {
    label: '限時免費領取',
    title: '《2026 不露臉 AI 音樂頻道變現指南》',
    subtitle: '完整拆解我兩個頻道的選題、製作、上架、營利流程。輸入 Email，立即免費寄到你的信箱。',
    bullets: [
      'AI 音樂頻道選題：3 分鐘判斷利基有沒有錢途',
      'Suno 出歌提示詞模板，複製就能生成原創音樂',
      '頻道封面 / MV 視覺的 AI 製作 SOP',
      '90 天從 0 到開通 YouTube 營利的行動清單',
    ],
    buttonText: '免費寄給我',
    boxTitle: 'AI 音樂變現指南',
    boxSubtitle: 'PDF 實戰手冊',
    privacyText: '承諾不發送垃圾郵件，隨時可取消訂閱。',
  },
  faq: {
    label: '常見問題 · FAQ',
    sectionTitle: '開始前，你可能會問的 4 件事',
    items: [
      { q: 'AI 音樂頻道現在做，會不會太晚、太飽和了？', a: '音樂是「聽不膩」的剛需內容，市場每天都在長。重點不是早晚，而是有沒有用對標＋數據選對還沒被吃下的利基——我 4 月開課的學員，一個多月就開通營利。' },
      { q: 'AI 生成的音樂能營利嗎？版權、被檢舉怎麼辦？', a: '只要用合規工具生成原創音樂、不挪用他人素材，就能正常開通 YouTube 營利。課程會完整教你版權合規、原創聲明與避免被誤判的做法。' },
      { q: '要花多少錢、多久才看到第一筆收益？', a: 'AI 工具月成本台幣幾百元（Suno 等）。時間因人而異，但跟著 SOP 走、頻道達到 YouTube 營利門檻後就會開始累積收益；我的學員最快一個多月開通。' },
      { q: '我有正職、零基礎、不懂音樂，每天要花多久？', a: '整套流程設計成「下班後 1–2 小時可操作」。不需露臉、不需唱歌、不需樂理——AI 負責生成音樂與視覺，你負責選題與上架。' },
    ],
  },
  featuredTools: {
    sectionTitle: '免費 AI 工具箱',
    sectionSubtitle: '我自己在用的小工具，順手做給大家免費用。',
    linkText: '查看所有 AI 工具',
  },
  stats: {
    sectionTitle: '一人公司的變現實證',
    sectionSubtitle: '不喊口號，用我自己的頻道數據說話。',
    items: [
      { number: 30, suffix: ' 天', label: '虛擬歌手開通營利', sub: '唯夏 VXYA・從 0 到 1' },
      { number: 2, suffix: ' 萬+', label: '頻道月被動分潤', sub: 'ChillNight・YouTube 廣告' },
      { number: 3, suffix: ' 萬+', label: '單曲最高觀看', sub: '《辭雪樓》戲腔情歌' },
    ],
  },
  ctaBanner: {
    title: '準備好打造你的第一個 AI 音樂頻道了嗎？',
    subtitle: '加入社群，跟著正在用 AI 做不露臉頻道變現的創業者，領取你的第一份實戰指南。',
    buttonText: '免費領取指南',
  },
  stickyBar: {
    label: '限時免費 · 入門指南',
    title: '不露臉 AI 音樂頻道變現指南',
    highlight: '免費',
    buttonText: '免費領取',
  },
};

export type HomeDefaults = typeof DEFAULTS;
